### PR TITLE
added scenarios into the URL as search parameters

### PR DESCRIPTION
**Pull request by energynumbers**
Hi @olejandro ,

please can you check that this is sane & suitable?

I've added the scenarios (and the showDifference boolean flag) into the URL as search parameters; this is rather than having them as state properties which are propagated through the app.

This is to enable the sharing (e.g. by email to clients, or on social media) of URL links which directly to not only a specific set of Charts, but the Charts for a specific Main Scenario (together with a specific Compare Scenario).

It does introduce one backwards incompatibility: scenario names MUST now be made URI-safe before going into config.js and scenarioTitles.js

example URL: https://deploy-preview-29--energy-charts.netlify.app/charts/group1/subgroup1?s=Scenario2&c=Scenario3&d=1

And very best wishes for 2023.

### CODE REVIEW

**Comment by energynumbers** [comment]
NB It's quite possible that this breaks Scenario Groups. I haven't tried using Scenario Groups & variants yet. Are they actually enabled?

**Comment by olejandro** [comment]
Hola @energynumbers,

Happy 2023! Great to see this working. 😄
I'd like to keep scenario and diff selection as states and useSearchParams to initialise their initial values instead. This requires fewer changes and maintains my familiarity with the code. 😆 In this case one would also need to introduce a share button to enable link generation for sharing.
Would you like to give it a go? Or should I do it?

**Comment by energynumbers** [comment]
I did try it that way at first, but the more I got into it, the less satisfactory I found it. 

The difficulty with keeping them as internal states, is that you've then got to keep the url and the internal state in sync, throughout the code.

There'd no longer be a single source of truth.

So if the URL is always going to reflect the state anyway, then using internal state and prop drilling adds complexity and brittleness without any gain.

Could I urge you to take another look at this PR, play with it, look at it in the debugger?

I have quite high confidence that this - having the URL as the single source of truth on the state - is a strong solution. I do, however, have low confidence that my coding is the prettiest or most technically correct way to do it.

**Comment by olejandro** [comment]
@energynumbers, this is the behaviour I've been thinking of: https://deploy-preview-30--energy-charts.netlify.app/charts?scen1=Scenario+4&scen2=Scenario+3&diff=true (i.e. search parameters are not preserved in the URL while navigating the App).
The parameters still have to be checked for consistency before using them to initialise the states and some of the URLs need to be stripped of search parameters, but this has very few changes compared to the original code: https://github.com/facilitate-energy/energy-charts/pull/30/files
Did you try something similar?

**Comment by energynumbers** [comment]
@olejandro I did, yes, and I considered the lack of sync with the URL to be a deal-breaker.

Perhaps it's because I find it easiest to copy & paste from the browser address bar, that I forget that lots of other people prefer a share button. It will be a good addition, I guess.

**Comment by olejandro** [comment]
An alternative approach has been introduced by #30

**Comment by olejandro** [comment]
Thanks, @energynumbers!
In general, the need for changes like these should be first submitted as issues, so that they can be discussed.
For example, 4 and 5 are not needed, since the current scenario names are intentional. This [post](https://www.sistrix.com/ask-sistrix/technical-seo/site-structure/do-i-have-to-convert-the-spaces-in-urls) describes how spaces should be handled. Indeed [this](energy-charts.netlify.app/charts?scen1=Scenario+4) works well and the URL can be shared.
I don't see any problem with 3, while 1 and 2 are not how the App is intended to work. 🤷‍♂️
I will add contributing guidlines, so that it is clear how contributions can be made.

**Comment by olejandro** [comment]
@energynumbers, I believe #31 addresses your needs. Just update to v0.8.1 and include `showSearchParams: true` in config.

**Pull request closed without merging**
